//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR__PROJECT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRdbEntities1 : DbContext
    {
        public IRdbEntities1()
            : base("name=IRdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllPage> AllPages { get; set; }
        public virtual DbSet<bigram_index> bigram_index { get; set; }
        public virtual DbSet<InvertedIndex> InvertedIndexes { get; set; }
        public virtual DbSet<invertedindexcopy> invertedindexcopies { get; set; }
        public virtual DbSet<soundex_index> soundex_index { get; set; }
    }
}
