//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR__PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class soundex_index
    {
        public int id { get; set; }
        public string Soundex { get; set; }
        public string Term { get; set; }
    }
}
